### ISSUE TITLE
SNES audio issue

### ISSUE THREAD

**Issue by ghost** [wheatevo/wiiu-vc-extractor#1]
When extracting a snes rom, the audio is not correct.

**Comment by wheatevo** [comment]
Do you have more details on this issue? Which game are you seeing audio problems with and what kind of problems are experiencing? Also, what OS are you on and how are you playing the extracted rom?

Thanks!

**Comment by tomsterley** [comment]
I am using Super Mario World, and the only problem with it is the audio. I am on Windows 7 and am using the ZMZ emulator

**Comment by tomsterley** [comment]
Also, here is a audio dump of the title screen (Edited for loudness, and there is a couple cuts because my audio encoder used for zmz :/ )

**Comment by wheatevo** [comment]
Thanks for the information! I'll take a look.

**Comment by tomsterley** [comment]
Welp, whatevo floats your boat! (ba dum tss)

**Comment by tomsterley** [comment]
If you tell me where the PCM extraction code is located, i can probably fix it.

**Comment by tomsterley** [comment]
Oh and if it helps if you want to fix it: http://www.smwcentral.net/?p=map&type=rom

**Comment by wheatevo** [comment]
Well, the good news is that the data is being extracted, it just isn't being converted into BRR format (if you look at the files it produces they still have the chunks with PCMF signatures). I'm currently taking a look at the code from https://github.com/Plombo/vcromclaim/blob/master/snesrestore.py and https://github.com/Plombo/vcromclaim/blob/master/brrencode3.py since it does something similar.

**Comment by tomsterley** [comment]
I have found this article about SNES PCM and BRR: http://forum.xentax.com/viewtopic.php?f=17&t=5765

**Comment by Cornholio309** [comment]
A bit late to the party, but I made a post about this program on the subreddit /r/wiiuhacks, where I also pointed out this issue after testing a couple of SNES VC titles I own. I extracted Earthbound from it's official Wii U VC release with this tool, and I recorded video footage of the "sound bug" in action:

https://youtu.be/fAafrPLmTqs

For comparison, here's the same intro with accurate audio ("The War Against Giygas!" screen isn't skipped here like I did):

https://www.youtube.com/watch?v=g3dIWyvNoxM

I also tested Donkey Kong Country which had the same issue.

To confirm this wasn't an emulator bug at the time, I tested this ROM on both SNES9X-1.5.3 and BSNES Plus. Both have the same issue.

Many thanks for looking into this.

**Comment by wheatevo** [comment]
No worries, thanks for the additional information! I know what needs to be done and the changes should be finished by this weekend.

**Comment by wheatevo** [comment]
I currently have this working for Super Mario World, I just need to change the code a bit so it can handle PCMF entries at any arbitrary location in the rom (since though SMW has all of the PCMF entries at the end, some roms have them throughout or in the middle).

**Comment by tomsterley** [comment]
Well that's inconvenient. Why not just place PCM data at the end of every game nintendo?

**Comment by tomsterley** [comment]
Don't worry, I am the ghost. I just deleted my acc so I could reset my data.

**Comment by wheatevo** [comment]
I went ahead and created a prerelease for the initial sound fixes. Feel free to download release 0.3.1 and let me know if it corrects your issues with Super Mario World.

The code currently injects the converted PCM -> BRR sound data throughout the rom but there seem to be some issues with games such as Super Metroid and Earthbound. I suspect that I am not properly identifying where the actual PCM data starts in those files (normally it starts after the rom in the .rpx file).

**Comment by tomsterley** [comment]
This has indeed fixed my issue for SMW, Thanks!

**Comment by Hking0036** [comment]
With this version I get a:

`Unhandled Exception: System.InvalidOperationException: Could not find any PCM data within the SNES VC rom.`
BoF1 + Dracula X.

I'm sure you're aware of this because it's just a pre-release but I figured I'd through it out there.

**Comment by wheatevo** [comment]
@Hking0036 That issue should now be corrected in the latest release.

**Comment by Hking0036** [comment]
@wheatevo thanks. Dracula X dumped correctly, however I found the rom matches the USA no-intro ([http://datomatic.no-intro.org/?page=show_record&s=49&n=0400](here))

When dumped from RAM I get a CRC32 of E0D610A8.

I'm going to try redumping but I think this might be the on-the-fly patching bogeyman I've been hearing about and if that's the case there's really no way around that.

**Comment by tomsterley** [comment]
@Hking0036 are you extracting a .rpx/.rpl dumped with ddd?

**Comment by Hking0036** [comment]
Of course, I don't entirely know what else I _would_ be using but yes, I'm using a DDD dump.

**Comment by Cornholio309** [comment]
The preview versions seem to be working really nice with the ROMS I've tested. I've tried Super Mario World, Kirby Super Star, Donkey Kong Country, and Earthbound.

All of them except Earthbound seemingly restored the audio correctly based on around 2 minutes of gameplay each. Thanks so much for the excellent work!

**Comment by potatomatato** [comment]
I know this is a fairly old issie, but has anyone looked into fixing the audio with Earthbound? I am trying to play the rom, but its just not the same without the original audio...

**Comment by wheatevo** [comment]
@potatomatato I will take a look at a bit later today and see if I can dig anything up--I need to compare how the rom I am extracting ends up differing from a properly dumped Earthbound.

**Comment by wheatevo** [comment]
A bit more information on Earthbound specifically:
* Rom maps: http://datacrystal.romhacking.net/wiki/EarthBound:ROM_map and http://starmen.net/pkhack/misc/range_files.txt
* BRR data locations: http://pkhack.fobby.net/misc/spc/samples.txt

**Comment by wheatevo** [comment]
Differences between clean dump and VC extraction output:

```
0x0BE04A-0x0BFEBC (Background data to 0x0BE229, sound data to 0xC01FF)
0x10E3C4-0x10FF81 (Sound data)
0x1CE057-0x1CF8A2 (Map music overlay data to 0x1CE236, sound data to 0x1D0200)
0x20ED22-0x20FCBF (Summers town map gfx to 0x20EF02, sound data to 0x2101FF)
0x220078-0x2241A6 (Sound data to 0x2E93FF)
0x224236-0x22539D (Sound data to 0x2E93FF)
0x22648F-0x22773B (Sound data to 0x2E93FF)
0x227818-0x22ECFE (Sound data to 0x2E93FF)
0x23002C-0x235F21 (Sound data to 0x2E93FF)
0x235F93-0x23FD7E (Sound data to 0x2E93FF)
0x240020-0x245117 (Sound data to 0x2E93FF)
0x245189-0x24EEAF (Sound data to 0x2E93FF)
<...many more differences between 0x24EEAF and 0x2D1E1A which is still the sound data region containing ~197 BRR samples...>
0x2D1E1A-0x2D27D3 (Sound data to 0x2E93FF)
0x2D6C16-0x2D73D5 (Sound data to 0x2E93FF)
```

Need to check individual BRR samples for conversion accuracy.

**Comment by wheatevo** [comment]
Issue has been identified--the problem is the incorrect size determination logic. Earthbound is being seen as a 32mbit rom instead of a 24mbit rom which means that we ignore part of the uncompressed PCM waveform data stored in the decompressed rpx file (the first 8mbit of it). When the size is hardcoded to 3,145,728 bytes, this issue does not occur.

Going to need to add code that can accurately determine rom size (since the rom size in the SNES header is rounded to nearest 8mbit). Should be able to use the CRC check information to determine this concretely.

**Comment by wheatevo** [comment]
This issue has been resolved in release 0.4.0:
https://github.com/wheatevo/wiiu-vc-extractor/releases/tag/0.4.0

**Comment by wheatevo** [comment]
If anyone is interested in more background on the issue, http://problemkaputt.de/fullsnes.htm#snescartridgeromheader describes that the ROM size header entry is actually rounded up (since we only have 1mbit, 2mbit, 4mbit, 8mbit, 16mbit, 32mbit, 64mbit, etc as valid sizes).

**Comment by tomsterley** [comment]
Whatevo, what happened to you? You disappeared for like a year.

**Comment by wheatevo** [comment]
@tomsterley Got busy. :)

Figured I should take another look at this issue when I saw some pull requests come through and it ended up being a bit simpler than expected (prior I was concerned it might be an issue with the PCM -> BRR conversion as opposed to just being a silly sizing determination error).

**Comment by dengart** [comment]
@wheatevo were you ever able to determine why the end result differs from the dumps on the internet?

**Comment by wheatevo** [comment]
@dengart The differences I've seen seem to just be modifications that were made to the rom as part of the VC release--the PCM -> BRR audio pieces should now be converted correctly.

**Comment by tomsterley** [comment]
@wheatevo I swear I thought you died or something... I'm not really into the wiiu scene anymore though..
