### ISSUE TITLE
Metroid Zero Mission fails to extract

### ISSUE THREAD

**Issue by Whovian9369** [wheatevo/wiiu-vc-extractor#17]
I downloaded a copy of "Metroid: Zero Mission" via JNUSTool using a key from the Ticket on my Wii U, and went to use this wonderful tool on the Loadiine formatted game.

Sadly, it hasn't been able to find the rom in any of the versions that I've tried, including 0.4.0.

Output from the tool (and no, I don't know why it's giant and bolded, either):

```
Verbose output mode is set
Source extract file is D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\alldata.psb.m
============================================================================
Starting extraction of rom from D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\alldata.psb.m...
============================================================================
PSB file detected!
Decompressing PSB file...
Checking for PSB data file D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\alldata.bin...
Found rom subfile at abmxe0.e77.m
    Offset: 33744896
    Length: 5233762
Decompressing rom...
Decompressing PSB file...
Checking if this is a GBA VC title...
Checking D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\abmxe0.e77.m.extract...
============================================================================
FAILURE: Could not successfully identify the rom type for D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\alldata.psb.m
============================================================================
```

Any and all assistance would be very appreciated! (Thank you again for the amazing tool, by the way!)

**Comment by wheatevo** [comment]
This is likely due to the verification code that ensures the GBA header is valid--my best guess is that the rom title has a colon in it. I will push a fix once I have determined all of the valid GBA title characters so that you can retest.

**Comment by Whovian9369** [comment]
Alright, thank you very much!

**Comment by wheatevo** [comment]
[testtitlegbafix.zip](https://github.com/wheatevo/wiiu-vc-extractor/files/1261839/testtitlegbafix.zip)

Here is a test release--go ahead and download it and let me know if it fixes your issue.

**Comment by Whovian9369** [comment]
`============================================================================
Starting extraction of rom from D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\alldata.psb.m...
============================================================================
PSB file detected!
Decompressing PSB file...
Checking for PSB data file D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\alldata.bin...
Found rom subfile at abmxe0.e77.m
    Offset: 33744896
    Length: 5233762
Decompressing rom...
Decompressing PSB file...
Checking if this is a GBA VC title...
Checking D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\abmxe0.e77.m.extract...
============================================================================
FAILURE: Could not successfully identify the rom type for D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\alldata.psb.m
`
Something about this FEELS closer...

**Comment by wheatevo** [comment]
Hmm.. I'm going to go ahead and add better logging around the GBA extractor so that we can get a better idea of what is not passing.

**Comment by Whovian9369** [comment]
Well thank you very much for your time with this!

**Comment by wheatevo** [comment]
@Whovian9369 Here is another debug build--this includes more detailed logging. Please re-run the extract with the `-v` flag and let me know what you get back. We should be able to determine the issue from this.

[testtitlegbafix2.zip](https://github.com/wheatevo/wiiu-vc-extractor/files/1262034/testtitlegbafix2.zip)

**Comment by Whovian9369** [comment]
GBA Boot Bitmap, it looks like!

```$ ./WiiuVcExtractor.exe -v "D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\alldata.psb.m"
Verbose output mode is set
Source extract file is D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\alldata.psb.m
============================================================================
Starting extraction of rom from D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\alldata.psb.m...
============================================================================
PSB file detected!
Decompressing PSB file...
Checking for PSB data file D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\alldata.bin...
Found rom subfile at abmxe0.e77.m
    Offset: 33744896
    Length: 5233762
Decompressing rom...
Decompressing PSB file...
Checking if this is a GBA VC title...
Checking D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\abmxe0.e77.m.extract...
GBA Header data: FE-0F-1E-EA-24-FF-AE-51-69-9A-A2-21-3D-84-82-0A-84-E4-09-AD-11-24-8B-98-C0-81-7F-21-A3-52-BE-19-93-09-CE-20-10-46-4A-4A-F8-27-31-EC-58-C7-E8-33-82-E3-CE-BF-85-F4-DF-94-CE-4B-09-C1-94-56-8A-C0-13-72-A7-FC-9F-84-4D-73-A3-CA-9A-61-58-97-A3-27-FC-03-98-76-23-1D-C7-61-03-04-AE-56-BF-38-84-00-40-A7-0E-FD-FF-52-FE-03-6F-95-30-F1-97-FB-C0-85-60-D6-80-25-A9-63-BE-03-01-4E-38-E2-F9-A2-34-FF-BB-3E-03-44-78-00-90-CB-88-11-3A-94-65-C0-7C-63-87-F0-3C-AF-D6-25-E4-8B-38-0A-AC-72-21-D4-F8-07-5A-45-52-4F-4D-49-53-53-49-4F-4E-45-42-4D-58-45-30-31-96-00-00-00-00-00-00-00-00-00-00-1D-00-00
Checking for GBA boot bitmap...
Could not find GBA boot bitmap! GBA rom not found.
============================================================================
FAILURE: Could not successfully identify the rom type for D:\Games\WiiU\Tools\JNUSTool\Metroid Zero Mission [PAWE01]\content\alldata.psb.m
============================================================================
```

**Comment by wheatevo** [comment]
So it looks like the first three bytes: `FE 0F 1E` are not `2E 00 00` as expected--this is a bug where we are checking the entry point in the header in addition to the GBA bitmap. I will change this to ignore the first 4 bytes so that this should work.

**Comment by wheatevo** [comment]
@Whovian9369 This issue should now be resolved in release https://github.com/wheatevo/wiiu-vc-extractor/releases/tag/0.4.1. Let me know if that does not fix the issue and I will reopen it.

**Comment by Whovian9369** [comment]
Worked perfectly, @wheatevo ! I got the checksum of `2ea5e30681dc7aab3258535debbddfb9aa245a8a`, which matches the No-Intro checksum for it. Thank you very much for your time!
