### ISSUE TITLE
Metroid Zero Mission doesn't extract properly.

### ISSUE THREAD

**Issue by CTOBN** [wheatevo/wiiu-vc-extractor#21]
Metroid Zero Mission does extract, but when I open the file in VBA-M I just get a white screen as shown below. Tried on both 0.4.1 and 0.4.2
![wuvcdissue2](https://user-images.githubusercontent.com/32233750/30779409-f62ae156-a0a4-11e7-9bf5-e31eea8375bc.png)

![wuvcdissue](https://user-images.githubusercontent.com/32233750/30779402-c722126c-a0a4-11e7-921e-bf30c519cb74.png)

**Comment by wheatevo** [comment]
@CTOBN 

Could you please re-run the extract with the -v flag and post the output here?

Also, what is the size of the produced file?

**Comment by CTOBN** [comment]
![wuvcdissue3](https://user-images.githubusercontent.com/32233750/30784722-8ad1e272-a10f-11e7-99bf-5b5c31555f76.PNG)
![wuvcdissue4](https://user-images.githubusercontent.com/32233750/30784724-8cb4b59c-a10f-11e7-8504-3a7523daf282.PNG)
![wuvcdissue5](https://user-images.githubusercontent.com/32233750/30784725-939395a4-a10f-11e7-9d9c-6c11179b4bfe.PNG)

**Comment by wheatevo** [comment]
Hmm, it seems like it is the right size and it is at least reading the header correctly, but the first 4 bytes of the header (the entry point) are `FE 0F 1E EA` instead of `2E 00 00 EA` which is what I would expect.

I will have to take a closer look at this release in particular.

**Comment by CTOBN** [comment]
That worked. Thank you.
