### ISSUE TITLE
NES extraction writes extra bytes it doesn't need to

### ISSUE THREAD

**Issue by Zowayix** [wheatevo/wiiu-vc-extractor#28]
When extracting NES ROMs, 16 more bytes are written to the end of the file than necessary. Overdumps will probably work fine in most cases, but for preservation purposes, you'd want to get as close to the original NES ROM as possible.

If I remove the 16 bytes at the end of outputted files with a hex editor, the files become identical to what a ROM dump would actually be from a NES cart (plus the iNES header), as evidenced by calculating the hash from the actual data minus that header and matching it against No-Intro or other known good dumps.

**Comment by wheatevo** [comment]
Good catch--I think is a bug in the rom size calculation (includes the header size in the rom size but then does not subtract it after writing the header separately from the body, whoops).

I will fix this later today once I have some time to test to make sure everything works as expected.
