### ISSUE TITLE
SNES should output with a .sfc extension

### ISSUE THREAD

**Issue by Zowayix** [wheatevo/wiiu-vc-extractor#29]
Very minor nitpick here. I have to nitpick it, though. I have to nitpick the usage of .smc every time I see it, because that's actually the extension of a SNES ROM with a Super Magic Card header. Since these don't have a copier header these should technically be .sfc instead.

Anyway, that's just a really minor nitpick, it's not really that important I guess.

**Comment by wheatevo** [comment]
Thanks for filing this issue--I will get this updated to the correct extension later today as well.
