### ISSUE TITLE
 [Enhancement] Nintendo DS Support

### ISSUE THREAD

**Issue by TBirdSoars** [wheatevo/wiiu-vc-extractor#38]
Nintendo DS games dumped via DDD are perfectly playable in emulators, even with the .srl extension they are dumped with. However, they cannot be played on original hardware through flash carts or on a 3DS with custom firmware. They also do not match the dump information found on no-intro. At least for Animal Crossing - Wild World, this is caused by two problems:
1. There is a 12288 byte block of what seems to be worthless data from offsets 0x1000 to 0x3FFF
    - Changing every byte to zero causes the file to match the decrypted dump on no-intro
2. The game data, starting at offset 0x4000, is decrypted, whereas DS games are normally encrypted
    - This can be fixed with a program called eNDryptS Advanced, as long as the file is .nds and the 12288 bytes have been made zeros

Overwriting the data with zeros and changing the file extension should be easy enough, but the encryption part is beyond the scope of this program. Does prepping DS games for eNDryptS seem like it's worth adding to the program? If so, I can work on it and open a pull request once it's done.

**Comment by wheatevo** [comment]
Is it possible to use the dumps via flash carts when they are still decrypted?

For this project I think it would make sense to try to convert the DS roms into a more standard format. Is there an open source version of eNDryptS Advanced available? If not, the encryption functionality could be reimplemented here instead. I think for now it makes sense to update the file extension and correct the data.

Related gbatemp post (not much info here): https://gbatemp.net/threads/how-do-you-convert-nintendo-ds-srl-into-decrypted-nds.400279/

The post did mention specific addresses, though:
`There is extra data in the WiiU .srl from 0x1000-0x33FF, 0x3600-0x3FFF`

**Comment by TBirdSoars** [comment]
I don't believe that they can be used while decrypted; I'm fairly certain that while loading the game, an actual DS has to decrypt a section of the ROM and if it fails, it just overwrites a section of the ROM in memory to make it unplayable:
https://corgids.wordpress.com/2017/07/28/booting-the-nintendo-ds-a-technical-summary/
> Nintendo saw it fit to encrypt most game ROMs using the Blowfish algorithm. However, this only happens within the first 2 KB of an 8 KB region called the “secure area.” The first eight bytes of the secure area consist of the double encrypted string “encryObj” – if decrypted successfully, this string is overwritten in memory with the word “0xE7FFDEFF”, but if not, the entire 2 KB is overwritten (as you can imagine, this doesn’t bode well for running the game). ROM dumps, however, tend to have this region already decrypted, so the emulator has to manually re-encrypt the secure area if one wishes to boot from the BIOS. Furthermore, as indicated above, the commands sent to the cartridge are also encrypted, so the emulator must decrypt them as well.

Also, from the FAQ that came with eNDryptS:
> Q: Why i need encrypted roms? I can't run them from flashcards!
A: Yes, thats true. U need encrypted roms for **$***.

Unfortunately, it doesn't seem like eNDryptS is open source. I can at least get the ROMs into a more standard format, but the encryption may be impossible.

**Comment by wheatevo** [comment]
Some of the devkitpro repos for the DS may have example implementations of this decryption: https://github.com/devkitPro/ndstool

**Comment by TBirdSoars** [comment]
Ah, thanks for the link, that definitely seems doable. 

Also, where did you get the lists of Virtual Console titles for the other extractors, or did you make them yourself?

**Comment by wheatevo** [comment]
The list at https://wiiubrew.org/wiki/Title_database is pretty good for that sort of info, though I originally remember using a different source for the GBA titles (though those are just the game codes as opposed to the Wii U codes so it makes sense).

**Comment by TBirdSoars** [comment]
So, I was wrong - the DS dumps from the Wii U are actually encrypted, meaning they can already be played on flash carts and emulators, but not on 3DS with Twilight Menu++. Considering there are already tools that handle decryption, and decryption _might_ be a mild copyright issue, I don't think it needs to be included in this program. Instead, the DS extractor in my fork cleans up the junk data to match no-intro's dump info and identifies and renames the files according to no-intro's database. I'll open a pull request soon.

**Comment by wheatevo** [comment]
Closing this ticket since it was resolved in #40
