### ISSUE TITLE
GBA - Replacing entry point unnessary?

### ISSUE THREAD

**Issue by Pr3ttyF1y** [wheatevo/wiiu-vc-extractor#44]
Thanks to some verifications, it seems that replacing an unexpected entry point in GBA maybe incorrect and generating dumps that are not original and would be considered modified:

[http://forum.no-intro.org/viewtopic.php?f=6&t=3672&p=22940#p22941](http://forum.no-intro.org/viewtopic.php?f=6&t=3672&p=22940#p22941)

**Comment by wheatevo** [comment]
That makes sense to me--the change can be reverted along with some other fixes.

**Comment by wheatevo** [comment]
Release https://github.com/wheatevo/wiiu-vc-extractor/releases/tag/0.8.1 contains this fix.
