### ISSUE TITLE
Cannot extract FDS VC title Bubble Bobble (WUP-FBWJ)

### ISSUE THREAD

**Issue by flingrocks** [wheatevo/wiiu-vc-extractor#47]
The Bubble Bobble game used for WiiU is the Famicom Disk System version, but the program fails to identify it. When trying to extract, I get the output:
```
RPX file detected!
Decompressing RPX file...
Decompression complete.
Checking if this is an NES VC title...
Checking WUP-FBWJ.rpx.extract...
Not an NES VC Title
Checking if this is an SNES VC title...
Checking WUP-FBWJ.rpx.extract...
Checking for the SNES WUP header
Not an SNES VC Title
Checking if this is a Famicom Disk System VC title...
Checking WUP-FBWJ.rpx.extract...
Not a FDS VC Title
============================================================================
FAILURE: Could not successfully identify the rom type for WUP-FBWJ.rpx
============================================================================
```
The first hindrance is an oversight with the pattern used to identify FDS titles. By inclusion of the 16th byte, it assumes the manufacturer is always Nintendo (01), but this game's manufacturer is Taito (C0) and thus it fails to pass.
01 2A 4E 49 4E 54 45 4E 44 4F 2D 48 56 43 2A ~~**01**~~

Next problem then is that this game also has a Side B. The program won't extract Side B.
Side B is marked by another header right after Side A data.
In this game, Side A is used for saving and the last level; Side B used for the rest. Game was modified to remove the prompts to switch sides. Seems the FDS VC emulator flips automatically.
Extracting and combining the data of Side A and B does produce a full working file. It is just a matter of having the program look for another side and extracting that too.

**Comment by TBirdSoars** [comment]
Interesting. I had assumed that there were no doubled sided Disk System games on Wii U when I added FDS extraction, on account of there not being an obvious way to switch sides in the Virtual Console UI (and not owning Bubble Bobble, only Lost Levels). I'll see what I can do. The header should be a quick enough fix.

**Comment by flingrocks** [comment]
Much appreciated, thanks!  On a side note, I must have purchased some form of Bubble Bobble for every system I own.

Probably might want to consider a solution that can adapt to handle multiple disks as well. The test progra[m](https://repl.it/repls/MenacingVengefulApplicationpackage#main.cs) I did beforehand would though I thought it was needless, but then recently I noticed FDS adventure titles like Shin Onigashima available for WiiU. After checking around, I can say it does contain the data of two double sided disks. I gather that each disk and side has a disk info header.

One possible method would be to check for more headers at 65536 byte intervals. Then use the header count in a loop to a combined block-copy converter routine, where `br.BaseStream.Position = romPosition + counter*65536`.
Of course there are many other ways to accomplish this goal too which are likely better.

**Comment by TBirdSoars** [comment]
OK, I've created a pre-release version on my fork that should handle double-sided games:
https://github.com/TBirdSoars/wiiu-vc-extractor/releases/tag/0.7.1.1.1

Please let me know if this works, and if possible, could you compare the output rom's checksum against the checksums found in the following links? It should match one of these:

https://datomatic.no-intro.org/index.php?page=show_record&s=31&n=0120
https://datomatic.no-intro.org/index.php?page=show_record&s=31&n=0297
https://datomatic.no-intro.org/index.php?page=show_record&s=31&n=0367
https://datomatic.no-intro.org/index.php?page=show_record&s=31&n=0333

If it works perfectly, I'll open a pull-request.

**Comment by flingrocks** [comment]
That looks pretty good. I can confirm, it is indeed working for extracting the double-sided title Bubble Bobble. Output is consistent with other tested avenues. Now while it doesn't extract the sparse multi-disk titles yet, sound logic is there to add it in easily later.

Checksums of the resulting headerless FDS-format file:
Type  | Value
------|--------
CRC32 | 1CFC87EC
MD5   | 82FAD6D7047964D26D122F153B67BDC9
SHA-1 | 72396FCDB53A05EEEAD09565827C614048EC3FCC

Well, file does not match the no-intro entries, but I figured it wouldn't since prompts to switch sides were somehow absent. Differs by the values of 53 bytes I think. Also, it turns out the manufacturing date of this one is reported as 1987-Sep-18 rather than Oct-19.
Converting resulting file back to QD with nulled CRCs does make a [match](https://datomatic.no-intro.org/?page=show_record&s=31&n=0349) with the extracted QD, so I believe it all is right on track.

By the way, FDS file plays fully but for emulators without automatic flipping, one needs to know when to flip since it won't halt and ask.

**Comment by TBirdSoars** [comment]
OK, nice! One last test - this one should be able to handle Shin Onigashima, and games with any number of disks and sides.
Could you please test Bubble Bobble again and Shin Onigashima, if you have that game? The new build is here:
https://github.com/TBirdSoars/wiiu-vc-extractor/releases/tag/0.8.1.2
And the checksums for Shin Onigashima are here:
https://datomatic.no-intro.org/?page=show_record&s=31&n=0280
https://datomatic.no-intro.org/?page=show_record&s=31&n=0360
https://datomatic.no-intro.org/?page=show_record&s=31&n=0279
https://datomatic.no-intro.org/?page=show_record&s=31&n=0322
https://datomatic.no-intro.org/?page=show_record&s=31&n=0378
https://datomatic.no-intro.org/?page=show_record&s=31&n=0359 (only this one, after converting from FDS to QD, should matter)

**Comment by flingrocks** [comment]
Superb! Fantastic work. From a read, I see no problems and feel like everything *should* work.
Re-tested Bubble Bobble with the new build and it extracted fine, with a file size of 131000 and same checksums as last listed.
Should be getting results back for Shin Onigashima shortly (......)
