### ISSUE TITLE
Mac and Linux releases extract with no file extension

### ISSUE THREAD

**Issue by lendunistus** [wheatevo/wiiu-vc-extractor#54]
Pretty self-explanatory. Extracting the .zip file for the Mac or Linux releases just gives you a file with no extension.

"Get Info" window for the Linux release:
![Screenshot 2021-07-03 at 09 25 44](https://user-images.githubusercontent.com/53618962/124345326-f38a0c80-dbe0-11eb-8068-cebc8b11a531.png)

What the files look like when extracted:
![Screenshot 2021-07-03 at 09 25 53](https://user-images.githubusercontent.com/53618962/124345329-f5ec6680-dbe0-11eb-8d38-2e4abc17d8a4.png)

For what it's worth, I tried renaming the Mac release wiiuvcextractor.app and after changing the permissions to allow it to launch, absolutely nothing happened (probably because I didn't have an rpx file in the directory in the first place, might test this later).

Is it normal behavior that the apps have no file extension because you're supposed to run them from the command line (according to the README)?

Thanks!

**Comment by wheatevo** [comment]
The lack of file extension is intentional.

It is similar to other tools such as [packer](https://www.packer.io/) where you are intended to extract the executable to a location in your `PATH` (like `/usr/bin`), change permissions to allow it to be executed, and then use it from the command line.
